# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='mapperdata',
            name='center_lat',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='mapperdata',
            name='center_lon',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
