# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edc_map', '0003_auto_20170112_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDivision',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default='ckgathi', help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=25, null=True, unique=True, verbose_name='Label')),
                ('section_name', models.CharField(max_length=10, null=True)),
                ('sub_section_name', models.CharField(max_length=10, null=True)),
                ('map_area', models.CharField(max_length=25, null=True)),
                ('section_polygon', models.TextField(null=True)),
                ('sub_section_polygon', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='landmark',
            name='hostname_created',
            field=models.CharField(blank=True, default='ckgathi', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mapperdata',
            name='hostname_created',
            field=models.CharField(blank=True, default='ckgathi', help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
