# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_map', '0004_auto_20170209_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdivision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
