# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_map', '0005_auto_20170212_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdivision',
            old_name='section_polygon',
            new_name='container_polygon',
        ),
        migrations.RenameField(
            model_name='mapdivision',
            old_name='sub_section_polygon',
            new_name='in_container_polygon',
        ),
        migrations.RemoveField(
            model_name='mapdivision',
            name='user',
        ),
        migrations.AddField(
            model_name='mapdivision',
            name='username',
            field=models.CharField(editable=False, max_length=25, null=True, unique=True, verbose_name='Label'),
        ),
    ]
