# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils
import edc_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_map', '0007_auto_20170217_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default='ckgathi', help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('labels', edc_map.models.ListField(null=True)),
                ('container_name', models.CharField(max_length=10, null=True)),
                ('map_area', models.CharField(max_length=25, null=True)),
                ('container_boundry', edc_map.models.ListField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnerContainer',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default='ckgathi', help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('labels', edc_map.models.ListField(null=True)),
                ('username', models.CharField(editable=False, max_length=25, null=True, unique=True, verbose_name='Label')),
                ('inner_container_name', models.CharField(max_length=10, null=True)),
                ('inner_container_boundry', edc_map.models.ListField(null=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edc_map.Container')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemDivision',
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('container_name', 'map_area')]),
        ),
        migrations.AlterUniqueTogether(
            name='innercontainer',
            unique_together=set([('username', 'inner_container_name')]),
        ),
    ]
