# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_map', '0008_auto_20170221_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='container_boundry',
            new_name='boundry',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='container_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='innercontainer',
            old_name='inner_container_boundry',
            new_name='boundry',
        ),
        migrations.RenameField(
            model_name='innercontainer',
            old_name='inner_container_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='innercontainer',
            name='container',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edc_map.Container'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='innercontainer',
            name='username',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('name', 'map_area')]),
        ),
        migrations.AlterUniqueTogether(
            name='innercontainer',
            unique_together=set([('username', 'name')]),
        ),
    ]
