# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_map', '0009_auto_20170221_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='hostname_created',
            field=models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='innercontainer',
            name='hostname_created',
            field=models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='hostname_created',
            field=models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mapperdata',
            name='hostname_created',
            field=models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
