# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_map', '0010_auto_20170221_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innercontainer',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edc_map.Container'),
        ),
    ]
